name = "writing"
type = "webpack"
account_id = "cd4fb2c50dd11c531323586833df5eeb"
route = "preview.blakeembrey.com/*"
zone_id = "1f30b854a2b20f3baf56f0b90eb449ef"

[site]
bucket = "./out"
entry-point = "workers-site"

[env.production]
name = "writing-production"
routes = ["blakeembrey.com/*", "www.blakeembrey.com/*"]
